export function generateGPX(route: {
  name: string;
  geometry: { coordinates: [number, number, number?][] };
  elevation_profile?: [number, number][];
}): string {
  const points = route.geometry.coordinates;

  const trackpoints = points
    .map(([lng, lat, ele]) => {
      const eleTag = ele ? `<ele>${ele}</ele>` : "";
      return `      <trkpt lat="${lat}" lon="${lng}">${eleTag}</trkpt>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="STREAKR">
  <metadata>
    <name>${escapeXml(route.name)}</name>
    <desc>Generated by STREAKR — streakr.app</desc>
    <time>${new Date().toISOString()}</time>
  </metadata>
  <trk>
    <name>${escapeXml(route.name)}</name>
    <trkseg>
${trackpoints}
    </trkseg>
  </trk>
</gpx>`;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
